FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY Back/model.py /app/
COPY Back/trained_model.joblib /app/

CMD ["python", "model.py"]