FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY Data/data1.csv Data/data2.csv /app/

COPY Back/datagen.py /app/

CMD ["python", "datagen.py"]